version: '3.8'
services:
  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    volumes:
      - type: bind
        source: ./prometheus/prometheus.yml
        target: /etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - '9090:9090'

  node-exporter:
    container_name: node-exporter
    image: prom/node-exporter:latest
    ports:
      - '9100:9100'

  grafana:
    container_name: grafana
    image: grafana/grafana
    volumes: 
      - type: bind
        source: ./grafana
        target: /var/lib/grafana

    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
    ports:
      - "3000:3000"